#!/usr/bin/python
from classes.data_dicts import *


DEFAULT_DATA_FILE_CSV = "resources/2012/IVS_2012.csv"
FILTERED_DATA_FILE_CSV = "resources/2012/IVS_2012_filtered.csv"
FILTERED_PROCESSED_DATA_FILE_CSV = "resources/2012/IVS_2012_PROCESSED.csv"
ALL_PROCESSED_DATA_FILE_CSV = "resources/2012/IVS_2012_ALL_PROCESSED.csv"
MDCEV_PROCESSED_DATA_FILE_CSV = "resources/2012/IVS_2012_MDCEV_ALL_PROCESSED.csv"


GENDER_STR = "GENDER"
AGEGROUP_STR = "AGEGROUP"
MARITAL_STR = "MARITAL"
PURPOSE_STR = "TRIP_PURPOSE"
PARTYPE_STR = "PARTYPE"
INT_BOOKING_STR = "INT_BOOKING"
PARENT_STR = "PARENT"
CUSTOMS_STR = "CUSTOMS"
PACKAGE_STR = "PACKAGE"
COUNTRY_STR = "COUNTRY"
AIRLINE_STR = "AIRLINE"
REGION1_STR = "REGN1"
REGION2_STR = "REGN2"
REGION3_STR = "REGN3"
REGION4_STR = "REGN4"
REGION5_STR = "REGN5"


MODIFIED_VARIABLES = [
    GENDER_STR, AGEGROUP_STR, MARITAL_STR, PURPOSE_STR, INT_BOOKING_STR,
    PARENT_STR, CUSTOMS_STR, PACKAGE_STR, COUNTRY_STR, AIRLINE_STR, PARTYPE_STR,
    REGION1_STR, REGION2_STR, REGION3_STR, REGION4_STR, REGION5_STR
]


DESTINATION_ALTERNATIVES_LIST = [
    'NSW-SYD', 'NSW-Non-SYD',
    'VIC-MEL', 'VIC-Non-MEL',
    'QLD-BNE', 'QLD-Non-BNE',
    'SA-ADL', 'SA-Non-ADL',
    'WA-PER', 'WA-Non-PER',
    'TAS-HBA', 'TAS-Non-HBA',
    'NT-DRW', 'NT-Non-DRW',
    'ACT-CAN'
]

DESTINATION_ALTERNATIVES_CODES = [
    '110', '1',
    '210', '2',
    '310', '3',
    '410', '4',
    '510', '5',
    '610', '6',
    '710', '7',
    '810'
]

Activity_WITH_IndCommunity = [
    'activ15',
    'activ16',
    'activ37',
]

Participate_AT_IndCommunity = [
    'OTHPURP21'
]


COMPULSORY_FIELDS = ['id', 'uno', 'sero', 'NUMSTOP']

ORIGIN_LIST = ['ORIGIN_NSW', 'ORIGIN_VIC', 'ORIGIN_QLD', 'ORIGIN_SA', 'ORIGIN_WA', 'ORIGIN_TAS', 'ORIGIN_NT', 'ORIGIN_ACT']
ORIGIN_CODE = [['1', '2'], ['3', '4'], ['5', '6'], ['7', '8'], ['9', '10'], ['11'], ['12'], ['13']]

PARENT_LIST = ['PARENT_YES', 'PARENT_NO', 'PARENT_DONT_KNOW']
PARENT_CODE = [['1'], ['0', '2'], ['9']]

YOUNGEST_LIST = ['YOUNGEST_ZERO_TO_FIVE', 'YOUNGEST_SIZX_TO_TEN', 'YOUNGEST_ELEVEN_TO_FOURTEEN', 'YOUNGEST_DONT_KNOW']
YOUNGEST_CODE = [['1'], ['3'], ['4'], ['9']]

CH15TO24_LIST = ['CH15TO24_YES', 'CH15TO24_NO', 'CH15TO24_DONT_KNOW']
CH15TO24_CODE = [['1'], ['0', '2'], ['9']]

GENDER_LIST = ['GENDER_MALE', 'GENDER_FEMALE']
GENDER_CODE = [['1'], ['2']]

MARITAL_LIST = ['MARITAL_SINGLE', 'MARITAL_COUPLE', 'MARITAL_REFUSED']
MARITAL_CODE = [['1'], ['2'], ['9']]

EMPLOYMENT_LIST = ['EMPLOYMENT_WORKING', 'EMPLOYMENT_NOT_WORKING', 'EMPLOYMENT_RETIRED', 'EMPLOYMENT_STUDYING', 'EMPLOYMENT_DONT_KNOW']
EMPLOYMENT_CODE = [['1', '2', '5'], ['3'], ['4'], ['6'], ['7', '8', '9']]

HOUSINC_LIST = ['HOUSINC_LOW', 'HOUSINC_MEDIUM', 'HOUSINC_HIGH', 'HOUSINC_DONT_KONW']
HOUSINC_CODE = [['1', '2', '3', '4', '5'], ['6', '7', '8', '9'], ['11', '12'], ['10', '13', '99', '25', '28', '29']]

LIFECYCLE_LIST = ['LIFECYCLE_SINGLE', 'LIFECYCLE_COUPLE_NO_KIDS', 'LIFECYCLE_COUPLE_WITH_KIDS', 'LIFECYCLE_DONT_KNOW']
LIFECYCLE_CODE = [['1', '2', '3', '8', '9'], ['4', '10', '11'], ['5', '6', '7'], ['0']]

AGEGROUP_LIST = ['AGEGROUP_15_29', 'AGEGROUP_30_39', 'AGEGROUP_40_49', 'AGEGROUP_50_59', 'AGEGROUP_60_69', 'AGEGROUP_70_MORE']
AGEGROUP_CODE = [['1', '2', '3'], ['4', '5'], ['6', '7'], ['8', '9'], ['10', '11'], ['12', '13', '14']]

PARTYPE_LIST = ['PARTYPE_UNACCOMPANIED', 'PARTYPE_ADULT_COUPLE', 'PARTYPE_FAMILY_GROUP', 'PARTYPE_FREIEND_RELATIVES', 'PARTYPE_BUSINESS_ASSOCIATES', 'PARTYPE_SCHOOL_TOUR']
PARTYPE_CODE = [['1'], ['2'], ['3'], ['4'], ['5'], ['6']]

GROUPTYPE_LIST = ['GROUPTYPE_SPORTING', 'GROUPTYPE_SPECIAL_INTEREST', 'GROUPTYPE_GUIDED_HOLIDAY', 'GROUPTYPE_BUSINESS_OR_CONVENTION', 'GROUPTYPE_OTHER', 'GROUPTYPE_SCHOOL_EXCURSION']
GROUPTYPE_CODE = [['1'], ['2'], ['3'], ['4'], ['5', '8'], ['6']]

TRIP_PURPOSE_LIST = ['TRIP_PURPOSE_HOLIDAY', 'TRIP_PURPOSE_VISITING_FR', 'TRIP_PURPOSE_BUSINESS', 'TRIP_PURPOSE_EMPLOYMENT', 'TRIP_PURPOSE_EDUCATION', 'TRIP_PURPOSE_OTHER']
TRIP_PURPOSE_CODE = [['1'], ['2'], ['3', '4'], ['5'], ['6'], [str(x) for x in range(7, 99)]]

CUSTOMS_LIST = ['CUSTOMS_ENTRY_NSW', 'CUSTOMS_ENTRY_VIC', 'CUSTOMS_ENTRY_QLD', 'CUSTOMS_ENTRY_SA', 'CUSTOMS_ENTRY_TAS', 'CUSTOMS_ENTRY_NT', 'CUSTOMS_ENTRY_OTHER']
CUSTOMS_CODE = [['1'], ['2'], ['3', '7', '8', '11'], ['5'], ['9'], ['6'], ['4', '10', '98']]

COUNTRY_LIST = ["COUNTRY_USA", "COUNTRY_NEW_ZEALAND", "COUNTRY_ENGLAND", "COUNTRY_CHINA", "COUNTRY_JAPAN", "COUNTRY_GERMANY", "COUNTRY_CANADA", "COUNTRY_FRANCE", "COUNTRY_OTHER"]
COUNTRY_CODE = [['8104'], ['1201'], ['2102'], ['6101'], ['6201'], ['2304'], ['8102'], ['2303'], ['*']]


